variables:
  BUNDLE_PATH: vendor
  JEKYLL_ENV: production

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

cache:
  paths:
    - vendor
    - node_modules

stages:
  - build
  - deploy

build:
  stage: build
  image: node:16.3-alpine
  script:
    - yarn
    - yarn prod
  artifacts:
    paths:
      - assets/js

pages:
  stage: deploy
  image: ruby:3.0
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
