title: "Halivert"
name: "Halí"
description: >- # this means to ignore newlines until "baseurl:"
  Sitio de Halí Velázquez
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://halivert.github.io"
emptyArray: []
paginate: 7
paginate_path: "/blog/:num/"
timezone: "America/Mexico_City"

# Build settings
markdown: "kramdown"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Anonymous"
      permalink: "/blog/:year/:month/:title/"
      truncatewords: 60
      comments: true
      lang: "es_MX"
      hasmath: false
      hasinstantview: true
      imagealt: ""
  -
    scope:
      path: ""
    values:
      lang: "es_MX"
      searchbar: true
      logo: "/img/halivert-logo.png"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom
# list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock
  - yarn-error.log
