repository: "halivert/halivert.github.io"
title: "Halivert"
name: "Halí"
description: >- # this means to ignore newlines until "baseurl:"
  Sitio de Halí Velázquez
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://halivert.dev"
paginate: 7
paginate_path: "/blog/:num/"
timezone: "America/Mexico_City"
logo: "/img/halivert-logo.png"
tagline: "Blog personal de un desarrollador"
lang: "es_MX"
twitter:
  username: "halivert"

markdown: "kramdown"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-github-metadata
  - jemoji
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: halivert
      permalink: "/blog/:year/:month/:title/"
      excerpt_separator: "<!-- Seguir leyendo -->"
      comments: true
      lang: "es_MX"
      has_math: false
      has_instant_view: true
      search_bar: true
      font_size: "is-size-5"
      image_types: "webp:image/webp,png:image/png"
  -
      scope:
        path: "blog"
      values:
        search_bar: true
  -
    scope:
      path: ""
    values:
      search_bar: false
      logo: "/img/halivert-logo.png"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom
# list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - yarn.lock
  - yarn-error.log
  - CNAME
  - /README.md
