name: Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: '16.3'
          cache: 'yarn'

      - name: Build JS files
        run: yarn && yarn prod

      - name: Save JS files
        uses: actions/upload-artifact@v2
        with:
          name: js-files
          path: assets/js/

  build:
    runs-on: ubuntu-latest
    needs: [build-js]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: js-files
          path: assets/js/

      - run: ls -R ${{ github.workspace }}/assets

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      # - name: Build Jekyll
      #   run: |
      #     # gem install --local bundler
      #     docker run \
      #     -v ${{ github.workspace }}:/srv/halivert \
      #     ruby:3.0 /bin/bash \
      #     -c "
      #       gem install bundler && \
      #       cd /srv/halivert && \
      #       bundle install && \
      #       jekyll build -b https://halivert.dev"
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - run: ls ${{ github.workspace }}
  # - name: Build the site
  #   uses: actions/download-artifact@v2
  #   env:
  #     JEKYLL_ENV: production
  #   with:
  #     name: js-files
  #   run: |
  #     docker run \
  #     -v ${{ github.workspace }}:/srv/halivert \
  #     -v ${{ github.workspace }}/_site:/srv/halivert/_site \
  #     jekyll/builder:latest /bin/bash \
  #     -c "cd /srv/halivert && jekyll build -b https://halivert.dev"
  # - name: Build the site
  #   uses: helaili/jekyll-action@v2
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   with:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  #     target_branch: "site"
