name: Jekyll site CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build yarn files
        uses: actions/checkout@v2
        uses: yarnpkg/dev:latest
        run: yarn prod

      - name: Build the site in the jekyll/builder container
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash \
          -c "chmod 775 /srv/jekyll && jekyll build --future"
