name: Jekyll site

on:
  push:
    branches:
      - main

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: "16.3"
          cache: "yarn"

      - name: Build JS files
        run: yarn && yarn prod

      - name: Save JS files
        uses: actions/upload-artifact@v2
        with:
          name: js-files
          path: assets/js/

  build:
    runs-on: ubuntu-latest
    needs: [build-js]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: js-files
          path: assets/js/

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: Build Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build -b https://halivert.dev

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: site

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: site
          folder: _site
