name: Jekyll site CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Echo information
        run: |
          docker run \
          yarnpkg/dev:latest ls

      - name: Build yarn files
        run: |
          docker run \
          yarnpkg/dev:latest /bin/bash \
          -c "yarn prod"

      - name: Build the site in the jekyll/builder container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash \
          -c "chmod 775 /srv/jekyll && jekyll build --future"
